name: Deploy to Cloud Run (stg)

on:
  push:
    branches:
      - main
      - feature/typescript

env:
  GCP_PROJECT_ID: google-cloud-project-id
  GCP_CLOUD_RUN_APP_NAME: scraping-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Build and Deploy
        run: |
          gcloud builds submit \
            --config cloudbuild.yaml \
            --substitutions _GCP_PROJECT_ID=$GCP_PROJECT_ID,_GCP_CLOUD_RUN_APP_NAME=$GCP_CLOUD_RUN_APP_NAME
          gcloud run deploy $GCP_CLOUD_RUN_APP_NAME \
            --image gcr.io/$GCP_PROJECT_ID/$GCP_CLOUD_RUN_APP_NAME \
            --timeout=15m \
            --concurrency 1 \
            --platform managed \
            --region asia-northeast1 \
            --memory=2Gi \
            --allow-unauthenticated
